version: "3.7"

services:
  ui:
    image: makevoid/comma_api_example_ui
    build:
      context: .
    ports:
      - 80:80
  api:
    image: makevoid/comma_api_example_api
    build:
      context: api
      args:
        - JWT_TOKEN
    # environment:
    #   # CORS_HOST: "http://localhost" # meeds to be overridden for your deployment, it is supported also as build-arg
    #   # JWT_TOKEN: "..." # soon, atm is a build arg, so I cannot publish the package to a public registry :)
    ports:
      - 3000:3000

  # dev-api
  #
  # api:
  #   image: makevoid/comma_api_example_api
  #   build:
  #     context: ../
  #     dockerfile: Dockerfile-dev
  #     args:
  #       - JWT_TOKEN
  #   ports:
  #     - 3000:3000
