version: "3.7"

services:
  ui:
    image: makevoid/comma_api_example_ui
    build:
      context: .
    ports:
      - 80:80
  api:
    image: makevoid/comma_api_example_api
    build:
      context: api
      args:
        - JWT_TOKEN
    ports:
      - 3000:3000

  # dev-api
  #
  # api:
  #   image: makevoid/comma_api_example_api
  #   build:
  #     context: ../
  #     dockerfile: Dockerfile-dev
  #     args:
  #       - JWT_TOKEN
  #   ports:
  #     - 3000:3000
