version: "3.7"

services:
  ui:
    image: makevoid/comma_api_example_ui
    build:
      context: .
    ports:
      - 80:80
  api:
    image: makevoid/comma_api_example_api
    build:
      context: api
    ports:
      - 3000:3000
